FROM node:24-alpine
WORKDIR /app
COPY package*.json ./

ARG PORT=3001
ARG NODE_ENV=production

RUN if [ "$NODE_ENV" = "production" ]; then \
  npm install --omit=dev; \
  else \
  npm install; \
  fi

COPY . .

RUN chown -R node:node /app
USER node
EXPOSE $PORT

CMD ["sh", "-c", "node server.js"]