FROM golang:1.26-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git go gcc

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG PORT=4000

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /ApplicationSrv main.go


FROM alpine:latest AS runtime
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/

COPY --from=builder /ApplicationSrv .

EXPOSE $PORT

CMD ["./ApplicationSrv"]